# docker-compose: enable test run

services:
  odoo:
    restart: "no"
    environment:
      - LOG_LEVEL=info
      - WITHOUT_DEMO=False
      - PIP_AUTO_INSTALL=1
      - DEBUGPY_ENABLE=0
      - ODOO_STAGE=test
    command: [
      "odoo-test", "--test-enable",
      "--database", "test_odoo",
      "--base-addons", "${BASE_MODULES:-base}",
      "--get-addons", "${TEST_MODULE_PATH:-$ODOO_EXTRA_ADDONS}",
      "--addons", "${INSTALL_MODULES:-}",
      "--test-tags=-tour",
    ]
