services:
  odoo:
    ports:
    - "8069:8069"
    #- "8072:8072"
    #- "41234:41234"
    #volumes:
    #- ../odoo:/opt/odoo:cached
    #- ../odoo-addons:/opt/odoo-addons:cached
    #- ${BACKUP_PATH}:/mnt/backup
    #cap_add:
    #- SYS_PTRACE  # for sampling
  db:
    mem_limit: 8G
    volumes:
      - ./scripts/db_tune.sql:/docker-entrypoint-initdb.d/db_tune.sql:ro
